// tickets endPoints

const GET_ALL_ACTIVE_TICKETS = "superAdmin :  GET_ALL_ACTIVE_TICKETS" ;
const DELETE_SPECIFIC_TICKET = "superAdmin : DELETE_SPECIFIC_TICKET"
const SEARCH_FOR_TICKET = "superAdmin : SEARCH_FOR_TICKET"
const GET_ALL_CLOSED_TICKETS = "superAdmin : GET_ALL_CLOSED_TICKETS"
const SEND_ANSWER_ON_TICKET = "admin : SEND_ANSWER_ON_TICKET"


module.exports =  {

    GET_ALL_ACTIVE_TICKETS,
    DELETE_SPECIFIC_TICKET,
    SEARCH_FOR_TICKET,
    SEND_ANSWER_ON_TICKET,
    GET_ALL_CLOSED_TICKETS

}